### ISSUE TITLE
Enchant table crash.

### ISSUE THREAD

**Issue by chaixshot** [fedpol1/enchantips#6]
If don't put Lapis Lazuli into the slot and hover on right panel the game will crash.
```
java.lang.IllegalStateException: Active scrollable tooltip section cannot be null.
	at com.fedpol1.enchantips.gui.ScrollableTooltipSection.setActiveSection(ScrollableTooltipSection.java:30)
	at net.minecraft.class_486.handler$zhd000$enchantips$enchantipsInjectRenderExtraEnchantments(class_486.java:543)
	at net.minecraft.class_486.method_25394(class_486.java:187)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$309(class_757.java)
	at net.minecraft.class_757.wrapOperation$bej000$fabric-screen-api-v1$onRenderScreen(class_757.java:3111)
	at net.minecraft.class_757.method_3192(class_757.java:931)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by fedpol1** [comment]
Need more info - Minecraft version, Enchantips version, Fabric API version

**Comment by chaixshot** [comment]
Minecraft: **1.20.4**
Fabric: **0.15.10**
Fabric: **Api 0.97.0**
[crash-2024-04-29_06.15.35-client.txt](https://github.com/fedpol1/enchantips/files/15144155/crash-2024-04-29_06.15.35-client.txt)

**Comment by fedpol1** [comment]
Was able to reproduce, still no idea what the cause is

**Comment by chaixshot** [comment]
![image](https://github.com/fedpol1/enchantips/assets/13221018/6e99e1b1-b52b-4523-b8d7-37af1053c5e3)
For now i just disable this thing to temporarily fix.

**Comment by chaixshot** [comment]
Ok, it crash with and without **Lapis Lazuli** while enchant.
And it only crash with **Possible Enchantments** enable and multiplayer server offline play never crash.
Mostly crash happen when point cursor to 30 lev enchant slot.

**Comment by dovidas147** [comment]
@chaixshot Can confirm, i've provided a PR https://github.com/fedpol1/enchantips/pull/7 for this project to fix this. Grab a build from the PR and test it if you are still interested


> Ok, it crash with and without **Lapis Lazuli** while enchant. And it only crash with **Possible Enchantments** enable and multiplayer server offline play never crash. Mostly crash happen when point cursor to 30 lev enchant slot.
