### ISSUE TITLE
Version for 1.21

### ISSUE THREAD

**Issue by ReneMuetti** [fedpol1/enchantips#8]
Hello
The MOD is not compatible with MC1.21. There is a crash when rendering:
```
[08:26:59] [main/WARN]:
 Error loading class: net/minecraft/class_1886 (java.lang.ClassNotFoundException: net/minecraft/class_1886)
[08:26:59] [main/WARN]:
 @Inject(@At("INVOKE")) Shift.BY=2 on travelersbackpack.mixins.json:HandledScreenMixin from mod travelersbackpack::handler$dbm000$travelersbackpack$mouseClicked exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[08:26:59] [main/WARN]:
 Failed to get system info for GL Caps
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:140) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:135) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:527) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:70) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2547) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2517) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:210) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
```
Is an upgrade to the current MC version planned?

**Comment by Dovias** [comment]
Working for a PR to this. Stay tuned

**Comment by Dovias** [comment]
> Hello The MOD is not compatible with MC1.21. There is a crash when rendering:
> 
> ```
> [08:26:59] [main/WARN]:
>  Error loading class: net/minecraft/class_1886 (java.lang.ClassNotFoundException: net/minecraft/class_1886)
> [08:26:59] [main/WARN]:
>  @Inject(@At("INVOKE")) Shift.BY=2 on travelersbackpack.mixins.json:HandledScreenMixin from mod travelersbackpack::handler$dbm000$travelersbackpack$mouseClicked exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
> [08:26:59] [main/WARN]:
>  Failed to get system info for GL Caps
> java.lang.IllegalStateException: Rendersystem called from wrong thread
> 	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:140) ~[client-intermediary.jar:?]
> 	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:135) ~[client-intermediary.jar:?]
> 	at com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:527) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6396.method_37123(class_6396.java:70) [client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_37274(class_310.java:2547) [client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_22681(class_310.java:2517) [client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:210) [client-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
> ```
> 
> ```
> [17:54:01] [main/ERROR]:
>  Mixin apply for mod enchantips failed enchantips.mixins.json:EnchantmentMixin from mod enchantips -> net.minecraft.class_1887: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Overwrite method method_8179 in enchantips.mixins.json:EnchantmentMixin from mod enchantips was not located in the target class net.minecraft.class_1887. Using refmap enchantips-refmap.json
> org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Overwrite method method_8179 in enchantips.mixins.json:EnchantmentMixin from mod enchantips was not located in the target class net.minecraft.class_1887. Using refmap enchantips-refmap.json
> 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
> 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:416) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
> 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:346) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
> 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
> 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
> 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:203) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.0.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.0.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
> 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
> 	at net.minecraft.class_9304.<clinit>(class_9304.java:36) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_9334.method_57899(class_9334.java:93) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_9334.method_57906(class_9334.java:276) [client-intermediary.jar:?]
> 	at net.minecraft.class_9334.<clinit>(class_9334.java:93) [client-intermediary.jar:?]
> 	at net.minecraft.class_1792$class_1793.method_57350(class_1792.java:195) [client-intermediary.jar:?]
> 	at net.minecraft.class_1792$class_1793.method_58406(class_1792.java:185) [client-intermediary.jar:?]
> 	at net.minecraft.class_1792.<init>(class_1792.java:98) [client-intermediary.jar:?]
> 	at net.minecraft.class_1739.<init>(class_1739.java:12) [client-intermediary.jar:?]
> 	at net.minecraft.class_1802.<clinit>(class_1802.java:43) [client-intermediary.jar:?]
> 	at net.minecraft.class_6089.method_9530(class_6089.java:64) [client-intermediary.jar:?]
> 	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1058) [client-intermediary.jar:?]
> 	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1054) [client-intermediary.jar:?]
> 	at net.minecraft.class_4970.method_9549(class_4970.java:355) [client-intermediary.jar:?]
> 	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1341) [client-intermediary.jar:?]
> 	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:869) [client-intermediary.jar:?]
> 	at net.minecraft.class_2246.<clinit>(class_2246.java:1259) [client-intermediary.jar:?]
> 	at net.minecraft.class_2358.method_10199(class_2358.java:336) [client-intermediary.jar:?]
> 	at net.minecraft.class_2966.method_12851(class_2966.java:52) [client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:130) [client-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
> [17:54:02] [main/WARN]:
>  @Inject(@At("INVOKE")) Shift.BY=2 on travelersbackpack.mixins.json:HandledScreenMixin from mod travelersbackpack::handler$dbl000$travelersbackpack$mouseClicked exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
> [17:54:02] [main/WARN]:
>  Failed to get system info for GL Caps
> java.lang.IllegalStateException: Rendersystem called from wrong thread
> 	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:140) ~[client-intermediary.jar:?]
> 	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:135) ~[client-intermediary.jar:?]
> 	at com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:527) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6396.method_37123(class_6396.java:70) [client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_37274(class_310.java:2547) [client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_22681(class_310.java:2517) [client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:210) [client-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
> ```
> 
> Is an upgrade to the current MC version planned?

Honestly, i've done some work on porting this 1.21 but, due to how 1.21 broke so many things with mod, and introduces data-driven enchantments that you can create via datapacks, this project really requires some refactoring in order for it to work properly. So i will not contribute to this project, simply because its not practical, and needs almost whole rewrite.

In my fork, mod launches successfully but there's lots of bugs and it crashes when viewing certains tooltips from the inventory guis. So I suggest not using it, if it will be even available till you see this message.

I might create a separate mod which does less (Display enchantment probabilities only) for 1.21 but im not quite sure. Sorry for false alarm of getting this mod updated to 1.21

**Comment by Dovias** [comment]
I guess mod author managed to update this to 1.21
